### ISSUE TITLE
SetDirection (Fan) Results in Error ID 7 - bard argument

### ISSUE THREAD

**Issue by ZippoD** [jbasen/Crestron---Bond-Bridge#1]
Hello,
I've got a fan that pulls "SetDirection" under action list, yet I am unable to set direction Forwards or Reverse - both print an error ID 7: bad argument. ToggleDirection does work. 

The Bond home app, copying OEM remote, calls the directions "Winter" and "Summer" and they do work. I wonder if that has something to do with error. Any ideas how to test further? Cheers.

**Comment by jbasen** [comment]
Hi,
After digging through the code I understand what is going on here.  Set direction is the only API command to require an argument (the direction) along with a state variable.  Both the argument and the state variable get put in the content string of the http request.  However, what isn't described in the API is what the content string needs to look like when the command has both an argument and state variable together.  I need to check with the folks at Bond so I can correct the code.  
Thanks

**Comment by ZippoD** [comment]
> 

Awesome. Let me know if you want me to run any tests for you. Thanks.

**Comment by ZippoD** [comment]
@jbasen - found another one:
My device actions indicate "StartIncreasingBrightness" and "StartDecreasingBrightness", presumably they need to be followed by "Stop" command on button release (this is for the light of the fan by the way). 
Seems like the device module doesn't have these inputs. Any of the "SetBrightness" analogs returns error.

**Comment by jbasen** [comment]
Thanks. I believe I know how to fix the setdirection issue. I’ll take a look at this as well. Hopefully I’ll have something for you to test later today or tomorrow

**Comment by jbasen** [comment]
Here is a version you can test:

https://1drv.ms/u/s!AjlldUMTB6AFgoF-1brmh_G6hpDUSQ?e=niCPjq

In this version there is a new bond.clz and a new v1.1 of the Bond Device module.  Both are required.

This should fix the issue you have with SetDirection.  Note that SetBrightness takes a value between 1 and 100 decimal.  Not 1% and 100% as is more common int the Crestron world.  Please validate that you are sending values between 1 and 100 decimal to the analog input on the module.  Finally, I purposefully didn't implement StartIncreasingBrightness and StartDecreasingBrightness for a couple of reasons.  First, they seem to be very rare commands and second I was very concerned about how they would even work due to latency in http commands.  

Let me know if this version addresses the issues you found.  If so I'll release it.  Note the clz file includes a fix for an issue experienced by another user in addition to the problems you are seeing.

Thanks

**Comment by ZippoD** [comment]
The fan direction is resolved - thank you. You didn't have to do it that quick :).

About the brightness - Yes, I was setting 1-100d (not%) and yes, still not working. About your concern of the hold/stop - the full dim level adjustment takes 7 seconds with OEM remote, so I don't think http delay will be noticeable. Also, Bond app has this implemented in the same fashion - when you press brightness up or down, that button changes it's label to "Stop" and you have to press it to simulate button released on OEM remote. How hard would it be to implement this? I don't mind using 0-100 analog, if it can be done. 

Btw, here is what the error prints when I change the level to 5d:

Bond-Send_Device_Action - Action: SetBrightness, Argument: 5, Device_ID: 374ba541
Bond-Send_Device_Action - URL: http://192.168.1.3/v2/devices/374ba145/actions/SetBrightness
Bond-Send_Device_Action - Error Sending Device Action: Crestron.SimplSharp.Net.Http.HttpException
   at Crestron.SimplSharp.Net.Http.HttpClient.Dispatch(HttpClientRequest aRequest)
   at Bond_Integration.Bond.Send_Device_Action(String Device_ID, String Action, String Argument)
   at UserModule_BOND_DEVICE_V1_1.UserModuleClass_BOND_DEVICE_V1_1.SETBRIGHTNESS_OnChange_35(Object __EventInfo__)
   at Amib.Threading.Internal.WorkItem.n()
   at Amib.Threading.Internal.WorkItem.Execute()
   at Amib.Threading.SmartThreadPool.f(WorkItem A_0)
   at Amib.Threading.SmartThreadPool.r()

**Comment by jbasen** [comment]
This is very weird.  The code that sends a command is common  to all the commands.  So, it shouldn't work for one command and throw an exception for another.  Just because it will provide a little more info can you please send me what you see in debugger when using this bond.clz

https://1drv.ms/u/s!AjlldUMTB6AFgoF_yi0T4cKoydE9RA?e=WDjibr

Also, can you send me the string of the actions for your fan.  

Thanks

**Comment by ZippoD** [comment]
I believe this is what you requested (deleted old clz, confitmed program wasn't compiling, added new clz and re-compiled/pushed update) :

16:24:05.595: Bond_1_Action_List$ -> "DecreaseSpeed","IncreaseSpeed","OEMRandom","OEMTimer","SetDirection","SetSpeed","StartDecreasingBrightness","StartIncreasingBrightness","Stop","ToggleDirection","ToggleLight","TogglePower","TurnLightOff","TurnLightOn","TurnOff","TurnOn".
16:25:59.642: [User Stimulus] : User set //Bond_1_SetBrightness to 5
16:25:59.720: //Bond_1_SetBrightness -> 5d
16:26:01.080: [Console Data] : Bond-Send_Device_Action - Error Sending Device Action: Crestron.SimplSharp.Net.Http.HttpException
16:26:01.080: [Console Data] :    at Crestron.SimplSharp.Net.Http.HttpClient.Dispatch(HttpClientRequest aRequest)
16:26:01.080: [Console Data] :    at Bond_Integration.Bond.Send_Device_Action(String Device_ID, String Action, String Argument)
16:26:01.080: [Console Data] :    at UserModule_BOND_DEVICE_V1_1.UserModuleClass_BOND_DEVICE_V1_1.SETBRIGHTNESS_OnChange_35(Object __EventInfo__)
16:26:01.080: [Console Data] :    at Amib.Threading.Internal.WorkItem.n()
16:26:01.080: [Console Data] :    at Amib.Threading.Internal.WorkItem.Execute()
16:26:01.080: [Console Data] :    at Amib.Threading.SmartThreadPool.f(WorkItem A_0)
16:26:01.080: [Console Data] :    at Amib.Threading.SmartThreadPool.r()
16:26:01.267: Bond_Bridge_Communications_Err_Msg$ -> Bond-Send_Device_Action - Error Sending Device Action: Crestron.SimplSharp.Net.Http.HttpException..   at Crestron.SimplSharp.Net.Http.HttpClient.Dispatch(HttpClientRequest aRequest)..   at Bond_Integration.Bond.Send_Device_Action(String Device_ID, St
16:26:01.267: //Bond_Bridge_Communications_Error -> 1
16:26:01.345: //Bond_Bridge_Communications_Error -> 0

**Comment by jbasen** [comment]
Thanks.  Mystery solved.  SetBrightness is not in the action list for your fan.  That is why when you try to set brightness you are getting an exception.  I'll look into implementing "StartDecreasingBrightness","StartIncreasingBrightness", and "Stop".  I don't believe it will be very difficult.

**Comment by jbasen** [comment]
Try this version.  I included the entire zip file but in reality the only thing new is a new version of the Bond Device Module (v 1.2).  This now includes the new commands you requested.

https://1drv.ms/u/s!AjlldUMTB6AFgoIAg3leKNCJi6shmg?e=UdLeyh

Let me know if they work.

Thanks

**Comment by ZippoD** [comment]
They indeed do! Thank you. 

For your help file - pulsing either will "jam" the device until "Stop" command is sent OR it seems like the hub times out after 20 seconds (I was watching the hub activity lights for this). I am going to implement finger release = send stop and I think this will be ok for everyone else that can read help files.

**Comment by jbasen** [comment]
I've posted V4
